name: Deploy React App to EC2 via VPN

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies & Build
        run: |
          npm install
          npm run build
          sudo apt-get update && sudo apt-get install -y openvpn
          echo "${{ secrets.VPN_CONFIG }}" | base64 -d > vpn-office1.ovpn
          chmod 600 vpn-office1.ovpn
          echo -e "${{ secrets.VPN_USER }}\n${{ secrets.VPN_PASSWORD }}" > vpn-auth.txt
          chmod 600 vpn-auth.txt
          sudo openvpn --config vpn-office1.ovpn --auth-user-pass vpn-auth.txt --daemon
          sleep 15
          echo "Checking tun0 interface..."
          if ip addr show tun0 > /dev/null 2>&1; then
           echo "VPN connected: tun0 interface is up"
           ip addr show tun0
          else
           echo "VPN connection failed"
          exit 1
          fi
          echo "Testing connectivity..."
          curl -s https://ifconfig.me || true
   
      # 8. Deploy build to EC2
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "build/*"
          target: "/var/www/demo/"

      # 9. Restart nginx on EC2
      - name: Restart nginx
        uses: appleboy/ssh-action@v0.1.6
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: sudo systemctl restart nginx

